### ISSUE TITLE
Conda recipe

### ISSUE THREAD

**Issue by stephanierobin** [rizkg/KmerInShort#1]
Dear @rizkg
I desperately need a bioconda package for your amazing kmerinshort tool.
While I will be skiing, could you make it next week please, and I will bring you a delicious bergamot lemon cake.
Thank you 
Stéphanie

ping @abretaud

**Comment by rizkg** [comment]
ok, that's a nice deal :)

**Comment by rizkg** [comment]
The recipe is available now 
https://anaconda.org/search?q=kmerinshort
